### PR TITLE
Add full CTM type

### PR DESCRIPTION
**Pull request by TJT01**

### CODE REVIEW

**Comment by tterrag1098** [comment]
How does this layout compare to Optifine's?

**Comment by TJT01** [comment]
LayoutComparison-export

Yeah, I think Optifine's layout looks better.

**Comment by TJT01** [comment]
Didn't like how the old layout looked, so I decided to change it.
New layout below:
NewLayout-export

**EDIT** Optifine layout for reference:
oftrimmed-export

**Comment by tterrag1098** [comment]
Implemented by https://github.com/Chisel-Team/ConnectedTexturesMod/commit/6de3569a8441a804582c2c025d55a7d8139d5f46

**Pull request closed without merging**
