### PR TITLE
Fix memory leak with RegionCache instances.

### PR DESCRIPTION
**Pull request by covers1624**
This PR fixes a major memory leak involving RegionCache. Basically the WeakHashMap CTM was storing instances of RegionCache in was never being cleaned by GC as RegionCache held a non weak reference to the key of the map (aswell as the annonomys lambda class inside RegionCache). Due to RegionCache's never being GC'd, it was common to have over 3GB of BlockPos instances just hanging around, This is easily noticeable with VisualVM. If profiling data is required before merge i can supply that, but its fairly self explanatory.

### CODE REVIEW

**Comment by covers1624** [comment]
Seems im horrible with git.. Tryna clean this up..

**Comment by covers1624** [comment]
Hmm, seems some files were commited to the repo with CRLF line endings, Linux is having none of it..

**Comment by tterrag1098** [comment]
Currently all the diffs are full file replacements, any way that could be fixed?

**Comment by covers1624** [comment]
Really the only changes that matter are in RegionCache and a comment i added in RenderContextList. The diff shows full file replacements because git on linux auto converts CRLF to LF, its expected that files on git should be in the LF format, windows git has an option enabled by default iirc to convert them to CRLF, unfortunately there isn't much i can do from my end, if you could covert the conflicting files to LF on the repo that would solve it.

EDIT: Lemme try a few things here real quick.

**Comment by tterrag1098** [comment]
Why not just disable autocrlf?

**Comment by covers1624** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/pull/69

**Pull request closed without merging**
